version: "2.1"
services:
  couchdb:
    image: "couchdb:3"
    container_name: "obsidian-livesync"
    restart: "unless-stopped"
    user: "1000:1000"
    environment:
      - "COUCHDB_USER=${COUCHDB_USER}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASS}"
    volumes:
      - "./data:/opt/couchdb/data:rw"
      - "./local.ini:/opt/couchdb/etc/local.ini:rw"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefic"
      - "traefik.http.routers.obsidian-livesync.rule=Host(`${OBS_DOMAIN}`)"
      - "traefik.http.routers.obsidian-livesync.entrypoints=websecure"
      - "traefik.http.routers.obsidian-livesync.service=obsidian-livesync"
      - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
      - "traefik.http.routers.obsidian-livesync.tls=true"
      - "traefik.http.routers.obsidian-livesync.tls.certresolver=tls"
      - "traefik.http.routers.obsidian-livesync.middlewares=obsidiancors"
      # The config for CORS to work on Traefik
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

networks:
  traefik:
    external: true
